name: Update Releases

on:
  release:
    types: [published, unpublished]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone Repository
        run: |
          git clone https://github.com/Ronin-Development-Official/.github.git .
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch Release Info
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ORG="Ronin-Development-Official"
          
          echo "Fetching repositories..."
          REPOS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/orgs/$ORG/repos" | \
            jq -r '.[].name')
          
          echo "Found repositories:"
          echo "$REPOS"
          
          BADGES=""
          
          echo "Checking for releases..."
          for REPO in $REPOS; do
            echo "Checking $REPO..."
            LATEST=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$ORG/$REPO/releases/latest")
            
            if [ "$(echo $LATEST | jq -r '.message')" != "Not Found" ]; then
              echo "Found release for $REPO"
              BADGE="[![${REPO^^}](https://img.shields.io/github/v/release/$ORG/$REPO?style=for-the-badge&logo=github&label=${REPO^^})](https://github.com/$ORG/$REPO/releases/latest)"
              BADGES="${BADGES}${BADGE}\n\n"
            else
              echo "No releases found for $REPO"
            fi
          done
          
          echo "Current README content:"
          cat README.md
          
          echo "Updating README with badges:"
          echo -e "$BADGES"
          
          sed -i -e "/<!-- BEGIN_RELEASES -->/,/<!-- END_RELEASES -->/c\<!-- BEGIN_RELEASES -->\n${BADGES}<!-- END_RELEASES -->" README.md
          
          echo "Updated README content:"
          cat README.md

      - name: Commit and Push Changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add README.md
          git commit -m "Update release badges"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Ronin-Development-Official/.github.git HEAD:main
